# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to='products/'),
        ),
    ]
