# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 18:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180902_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\ProjectsPyCharm\\ecommerce\\static_cdn\\protected_media_root'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
