# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-30 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BllingProfile',
            new_name='BillingProfile',
        ),
    ]
